"""
Lookup tables mapping short ROI area codes to full anatomical names.

Sources:
  HCP-MMP: Glasser et al. 2016, Nature (doi:10.1038/nature18933)
  SUIT:    Diedrichsen et al. SUIT cerebellar atlas

Flags:
  Area H    — labeled "Hippocampal Area H"; identity ambiguous in some HCP-MMP versions
              (EC is already separately listed; H may be a hippocampal subdivision)
  DVT       — relatively new HCP area; no widely adopted alternative anatomical name
  55b       — "Premotor-Prefrontal Transition Area"; functional role still being characterised
"""

HCP_NAMES: dict[str, str] = {
    "1":      "Primary Somatosensory Cortex, Area 1",
    "2":      "Primary Somatosensory Cortex, Area 2",
    "3a":     "Primary Somatosensory Cortex, Area 3a",
    "3b":     "Primary Somatosensory Cortex, Area 3b",
    "4":      "Primary Motor Cortex (M1)",
    "5L":     "Superior Parietal Cortex, Area 5L",
    "5m":     "Superior Parietal Cortex, Area 5m",
    "5mv":    "Superior Parietal Cortex, Area 5mv",
    "6a":     "Premotor Cortex, Area 6a (dorsal premotor)",
    "6d":     "Premotor Cortex, Area 6d (dorsal premotor)",
    "6ma":    "Supplementary Motor Area, Area 6ma",
    "6mp":    "Supplementary Motor Area, Area 6mp",
    "6r":     "Premotor Cortex, Area 6r (rostral premotor)",
    "6v":     "Premotor Cortex, Area 6v (ventral premotor)",
    "7AL":    "Superior Parietal Cortex, Area 7AL",
    "7Am":    "Superior Parietal Cortex, Area 7Am",
    "7m":     "Superior Parietal Cortex, Area 7m (medial)",
    "7PC":    "Superior Parietal Cortex, Area 7PC",
    "7PL":    "Superior Parietal Cortex, Area 7PL",
    "7Pm":    "Superior Parietal Cortex, Area 7Pm",
    "8Ad":    "Dorsolateral Prefrontal Cortex, Area 8Ad",
    "8Av":    "Dorsolateral Prefrontal Cortex, Area 8Av",
    "8BL":    "Dorsolateral Prefrontal Cortex, Area 8BL",
    "8BM":    "Dorsolateral Prefrontal Cortex, Area 8BM",
    "8C":     "Dorsolateral Prefrontal Cortex, Area 8C",
    "9-46d":  "Dorsolateral Prefrontal Cortex, Area 9/46d",
    "9a":     "Dorsolateral Prefrontal Cortex, Area 9a",
    "9m":     "Dorsolateral Prefrontal Cortex, Area 9m (medial)",
    "9p":     "Dorsolateral Prefrontal Cortex, Area 9p (posterior)",
    "10d":    "Frontopolar Cortex, Area 10d",
    "10pp":   "Frontopolar Cortex, Area 10pp (polar-polar)",
    "10r":    "Frontopolar Cortex, Area 10r (rostral)",
    "10v":    "Frontopolar Cortex, Area 10v (ventral)",
    "11l":    "Orbitofrontal Cortex, Area 11l",
    "13l":    "Orbitofrontal Cortex, Area 13l",
    "23c":    "Posterior Cingulate Cortex, Area 23c",
    "23d":    "Posterior Cingulate Cortex, Area 23d",
    "24dd":   "Mid-Cingulate Cortex, Area 24dd",
    "24dv":   "Mid-Cingulate Cortex, Area 24dv",
    "25":     "Subgenual Anterior Cingulate Cortex, Area 25",
    "31a":    "Posterior Cingulate Cortex, Area 31a",
    "31pd":   "Posterior Cingulate Cortex, Area 31pd",
    "31pv":   "Posterior Cingulate Cortex, Area 31pv",
    "33pr":   "Anterior Cingulate Cortex, Area 33pr",
    "43":     "Somatosensory-Motor Transitional Cortex, Area 43",
    "44":     "Broca's Area, Pars Opercularis (Area 44)",
    "45":     "Broca's Area, Pars Triangularis (Area 45)",
    "46":     "Dorsolateral Prefrontal Cortex, Area 46",
    "47l":    "Inferior Frontal Cortex, Area 47l",
    "47m":    "Inferior Frontal Cortex, Area 47m",
    "47s":    "Inferior Frontal Cortex, Area 47s",
    "52":     "Parainsular Cortex, Area 52",
    "55b":    "Premotor-Prefrontal Transition Area 55b",
    "A1":     "Primary Auditory Cortex, Area A1",
    "A4":     "Auditory Association Cortex, Area A4",
    "A5":     "Auditory Association Cortex, Area A5",
    "a9-46v": "Dorsolateral Prefrontal Cortex, Area 9/46v (anterior)",
    "a10p":   "Frontopolar Cortex, Area 10p (anterior)",
    "a24":    "Anterior Cingulate Cortex, Area 24 (anterior)",
    "a24pr":  "Anterior Cingulate Cortex, Area 24pr (anterior)",
    "a32pr":  "Anterior Cingulate Cortex, Area 32pr (anterior)",
    "a47r":   "Inferior Frontal Cortex, Area 47r (anterior)",
    "AAIC":   "Anterior Agranular Insular Complex",
    "AIP":    "Anterior Intraparietal Area",
    "AVI":    "Anterior Ventral Insular Area",
    "d23ab":  "Dorsal Posterior Cingulate Cortex, Area 23ab",
    "d32":    "Anterior Cingulate Cortex, Area 32 (dorsal)",
    "DVT":    "Dorsal Visual Transitional Area",
    "EC":     "Entorhinal Cortex",
    "FEF":    "Frontal Eye Field",
    "FFC":    "Fusiform Face Complex",
    "FOP1":   "Frontal Opercular Cortex, Area 1",
    "FOP2":   "Frontal Opercular Cortex, Area 2",
    "FOP3":   "Frontal Opercular Cortex, Area 3",
    "FOP4":   "Frontal Opercular Cortex, Area 4",
    "FOP5":   "Frontal Opercular Cortex, Area 5",
    "FST":    "Floor of the Superior Temporal Area",
    "H":      "Hippocampal Area H",
    "i6-8":   "Inferior Premotor-Prefrontal Transition Area 6-8",
    "IFJa":   "Inferior Frontal Junction, Anterior",
    "IFJp":   "Inferior Frontal Junction, Posterior",
    "IFSa":   "Inferior Frontal Sulcus, Anterior",
    "IFSp":   "Inferior Frontal Sulcus, Posterior",
    "Ig":     "Granular Insular Cortex",
    "IP0":    "Intraparietal Area 0",
    "IP1":    "Intraparietal Area 1",
    "IP2":    "Intraparietal Area 2",
    "IPS1":   "Intraparietal Sulcus Area 1",
    "LBelt":  "Lateral Belt Auditory Cortex",
    "LIPd":   "Lateral Intraparietal Area, Dorsal",
    "LIPv":   "Lateral Intraparietal Area, Ventral",
    "LO1":    "Lateral Occipital Cortex, Area 1",
    "LO2":    "Lateral Occipital Cortex, Area 2",
    "LO3":    "Lateral Occipital Cortex, Area 3",
    "MBelt":  "Medial Belt Auditory Cortex",
    "MI":     "Middle Insular Cortex",
    "MIP":    "Medial Intraparietal Area",
    "MST":    "Medial Superior Temporal Area",
    "MT":     "Middle Temporal Visual Area",
    "OFC":    "Orbitofrontal Cortex",
    "OP1":    "Parietal Opercular Cortex, Area OP1 (SII)",
    "OP2-3":  "Parietal Opercular Cortex, Areas OP2-3",
    "OP4":    "Parietal Opercular Cortex, Area OP4",
    "p10p":   "Frontopolar Cortex, Area 10p (posterior)",
    "p24":    "Anterior Cingulate Cortex, Area 24 (posterior)",
    "p24pr":  "Anterior Cingulate Cortex, Area 24pr (posterior)",
    "p32":    "Anterior Cingulate Cortex, Area 32 (posterior)",
    "p32pr":  "Anterior Cingulate Cortex, Area 32pr (posterior)",
    "p47r":   "Inferior Frontal Cortex, Area 47r (posterior)",
    "p9-46v": "Dorsolateral Prefrontal Cortex, Area 9/46v (posterior)",
    "PBelt":  "Parabelt Auditory Cortex",
    "PCV":    "Posterior Cingulate Visual Area",
    "PeEc":   "Perirhinal Ectorhinal Cortex",
    "PEF":    "Parietal Eye Field",
    "PF":     "Inferior Parietal Cortex, Area PF",
    "PFcm":   "Inferior Parietal Cortex, Area PFcm",
    "PFm":    "Inferior Parietal Cortex, Area PFm",
    "PFop":   "Inferior Parietal Cortex, Area PFop",
    "PFt":    "Inferior Parietal Cortex, Area PFt",
    "PGi":    "Inferior Parietal Cortex, Area PGi",
    "PGp":    "Inferior Parietal Cortex, Area PGp",
    "PGs":    "Inferior Parietal Cortex, Area PGs",
    "PH":     "Parahippocampal Cortex, Area PH",
    "PHA1":   "Parahippocampal Area 1",
    "PHA2":   "Parahippocampal Area 2",
    "PHA3":   "Parahippocampal Area 3",
    "PHT":    "Posterior Inferior Temporal Area PHT",
    "PI":     "Posterior Insular Cortex",
    "Pir":    "Piriform Cortex",
    "PIT":    "Posterior Inferotemporal Complex",
    "pOFC":   "Posterior Orbital Frontal Cortex",
    "PoI1":   "Posterior Insular Cortex, Area 1",
    "PoI2":   "Posterior Insular Cortex, Area 2",
    "POS1":   "Parieto-Occipital Sulcus Area 1",
    "POS2":   "Parieto-Occipital Sulcus Area 2",
    "PreS":   "Presubiculum",
    "ProS":   "Prosubiculum",
    "PSL":    "Perisylvian Language Area",
    "RI":     "Retroinsular Cortex",
    "RSC":    "Retrosplenial Cortex",
    "s32":    "Anterior Cingulate Cortex, Area 32 (subgenual)",
    "s6-8":   "Superior Premotor-Prefrontal Transition Area 6-8",
    "SCEF":   "Supplementary and Cingulate Eye Field",
    "SFL":    "Superior Frontal Language Area",
    "STGa":   "Superior Temporal Gyrus, Anterior",
    "STSda":  "Superior Temporal Sulcus, Dorsal Anterior",
    "STSdp":  "Superior Temporal Sulcus, Dorsal Posterior",
    "STSva":  "Superior Temporal Sulcus, Ventral Anterior",
    "STSvp":  "Superior Temporal Sulcus, Ventral Posterior",
    "STV":    "Superior Temporal Visual Area",
    "TA2":    "Temporal Area 2",
    "TE1a":   "Inferior Temporal Cortex, Area TE1a",
    "TE1m":   "Inferior Temporal Cortex, Area TE1m",
    "TE1p":   "Inferior Temporal Cortex, Area TE1p",
    "TE2a":   "Inferior Temporal Cortex, Area TE2a",
    "TE2p":   "Inferior Temporal Cortex, Area TE2p",
    "TF":     "Temporal Fusiform Cortex",
    "TGd":    "Temporal Pole, Dorsal",
    "TGv":    "Temporal Pole, Ventral",
    "TPOJ1":  "Temporo-Parieto-Occipital Junction Area 1",
    "TPOJ2":  "Temporo-Parieto-Occipital Junction Area 2",
    "TPOJ3":  "Temporo-Parieto-Occipital Junction Area 3",
    "V1":     "Primary Visual Cortex",
    "V2":     "Secondary Visual Cortex",
    "V3":     "Extrastriate Visual Cortex, Area V3",
    "V3A":    "Extrastriate Visual Cortex, Area V3A",
    "V3B":    "Extrastriate Visual Cortex, Area V3B",
    "V3CD":   "Extrastriate Visual Cortex, Area V3CD",
    "V4":     "Extrastriate Visual Cortex, Area V4",
    "V4t":    "Extrastriate Visual Cortex, Area V4t",
    "V6":     "Extrastriate Visual Cortex, Area V6",
    "V6A":    "Extrastriate Visual Cortex, Area V6A",
    "V7":     "Extrastriate Visual Cortex, Area V7",
    "V8":     "Extrastriate Visual Cortex, Area V8",
    "v23ab":  "Ventral Posterior Cingulate Cortex, Area 23ab",
    "VIP":    "Ventral Intraparietal Area",
    "VMV1":   "Ventromedial Visual Area 1",
    "VMV2":   "Ventromedial Visual Area 2",
    "VMV3":   "Ventromedial Visual Area 3",
    "VVC":    "Ventral Visual Complex",
}

SUIT_NAMES: dict[str, str] = {
    "I_IV":      "Cerebellar Lobules I-IV",
    "V":         "Cerebellar Lobule V",
    "VI":        "Cerebellar Lobule VI",
    "VIIb":      "Cerebellar Lobule VIIb",
    "VIIIa":     "Cerebellar Lobule VIIIa",
    "VIIIb":     "Cerebellar Lobule VIIIb",
    "IX":        "Cerebellar Lobule IX",
    "X":         "Cerebellar Lobule X",
    "CrusI":     "Cerebellar Crus I",
    "CrusII":    "Cerebellar Crus II",
    "Dentate":   "Dentate Nucleus",
    "Fastigial":  "Fastigial Nucleus",
    "Interposed": "Interposed Nucleus (Interpositus)",
}
